SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE `CONTAINS`;
TRUNCATE CUSTOMER;
TRUNCATE EMPLOYEE;
TRUNCATE MANAGER;
TRUNCATE `ORDER`;
TRUNCATE PRODUCT;
TRUNCATE REQUIRES;
TRUNCATE SHIPMENT;
TRUNCATE STORE_BRANCH;
TRUNCATE SUPPLIER;
TRUNCATE SUPPLIES;
TRUNCATE `TRANSACTION`;
TRUNCATE `USER`;
TRUNCATE WAREHOUSE;
TRUNCATE WORKS_AT;
SET FOREIGN_KEY_CHECKS = 1;

