SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE `CONTAINS`;
TRUNCATE CUSTOMER;
TRUNCATE EMPLOYEE;
TRUNCATE MANAGER;
TRUNCATE `ORDER`;
TRUNCATE PRODUCT;
TRUNCATE REQUIRES;
TRUNCATE SHIPMENT;
TRUNCATE STORE_BRANCH;
TRUNCATE SUPPLIER;
TRUNCATE SUPPLIES;
TRUNCATE `TRANSACTION`;
TRUNCATE `USER`;
TRUNCATE WAREHOUSE;
TRUNCATE WORKS_AT;
SET FOREIGN_KEY_CHECKS = 1;


CALL add_user ('Desmond', 'OBrien', 'abc*123', 'desmond@RR.ca', 1, 1)
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `add_user`(
	IN fname TEXT(255),
    IN lname TEXT(255),
    IN psswrd TEXT(255),
    IN eml TEXT(255),
    IN isManager INT,
    IN brnch_id INT
    )
BEGIN
INSERT INTO USER
VALUES (default, fname, lname, psswrd, eml);

SELECT @max_id := (SELECT MAX(user_id) FROM `USER`);


INSERT INTO EMPLOYEE
VALUES (@max_id, NOW());


IF	isManager = 1
	THEN INSERT INTO MANAGER VALUES (@max_id, default, brnch_id);
END IF;
END$$
DELIMITER ;
